In [2]:
import numpy

In [3]:
import matplotlib.pyplot as plt

In [4]:
%matplotlib inline

In [5]:
matplotlib inline

In [6]:
%magic

In [6]:
%timeit range(1000)

The slowest run took 5.35 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 669 ns per loop


In [25]:
import pickle
import numpy as np
import os

In [13]:
def load_CIFAR_batch(filename):
  """ load single batch of cifar """
  with open(filename, 'r') as f:
    datadict = pickle.load(f)
    X = datadict['data']
    Y = datadict['labels']
    X = X.reshape(10000, 3, 32, 32).transpose(0,2,3,1).astype("float")
    Y = np.array(Y)
    return X, Y

In [14]:
pickle.load()

TypeError: Required argument 'file' (pos 1) not found

In [15]:
plt.rcParams

RcParams({'agg.path.chunksize': 0,
          'animation.avconv_args': [],
          'animation.avconv_path': 'avconv',
          'animation.bitrate': -1,
          'animation.codec': 'mpeg4',
          'animation.convert_args': [],
          'animation.convert_path': 'convert',
          'animation.ffmpeg_args': [],
          'animation.ffmpeg_path': 'ffmpeg',
          'animation.frame_format': 'png',
          'animation.html': 'none',
          'animation.mencoder_args': [],
          'animation.mencoder_path': 'mencoder',
          'animation.writer': 'ffmpeg',
          'axes.axisbelow': False,
          'axes.edgecolor': 'k',
          'axes.facecolor': 'w',
          'axes.formatter.limits': [-7, 7],
          'axes.formatter.use_locale': False,
          'axes.formatter.use_mathtext': False,
          'axes.formatter.useoffset': True,
          'axes.grid': False,
          'axes.grid.axis': 'both',
          'axes.grid.which': 'major',
          'axes.hold': True,
          'a

In [16]:
a = np.array([[1,2],[5,2],[3,2],[4,2]])

In [17]:
np.argsort(a)

array([[0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

In [18]:
k = np.array([1,2,3,2,5,6,7,8,9])
count = {}
for i in k:
    count[i] = 0
for j in k:
    count[j] = count[j] + 1

In [19]:
k[0:2]

array([1, 2])

In [20]:
for n in count:
    print(n)

1
2
3
5
6
7
8
9


In [21]:
max(count)

9

In [22]:
a[0] = 1

In [23]:
a

array([[1, 1],
       [5, 2],
       [3, 2],
       [4, 2]])

In [24]:
b=np.array([1,2])

In [25]:
a-b

array([[ 0, -1],
       [ 4,  0],
       [ 2,  0],
       [ 3,  0]])

In [26]:
f=sum(a-b)*np.ones((1,2))

In [27]:
f

array([[ 9., -1.]])

In [28]:
np.rot90(f)

array([[-1.],
       [ 9.]])

In [29]:
np.repeat(sum(a-b),4)

array([ 9,  9,  9,  9, -1, -1, -1, -1])

In [30]:
np.ones((4,2))*np.array([[1],[2],[3],[4]])

array([[ 1.,  1.],
       [ 2.,  2.],
       [ 3.,  3.],
       [ 4.,  4.]])

In [31]:
c= [sum(l) for l in a-b]

In [32]:
list(c)

[-1, 4, 2, 3]

In [33]:
type(c)

list

In [34]:
np.array(c)

array([-1,  4,  2,  3])

In [35]:
d = a.tolist()

In [36]:
d

[[1, 1], [5, 2], [3, 2], [4, 2]]

In [37]:
np.array(d)

array([[1, 1],
       [5, 2],
       [3, 2],
       [4, 2]])

In [38]:
np.split(a,4)

[array([[1, 1]]), array([[5, 2]]), array([[3, 2]]), array([[4, 2]])]

In [39]:
a

array([[1, 1],
       [5, 2],
       [3, 2],
       [4, 2]])

In [40]:
e = np.rot90(a)
e

array([[1, 2, 2, 2],
       [1, 5, 3, 4]])

In [41]:
e[::-1]

array([[1, 5, 3, 4],
       [1, 2, 2, 2]])

In [42]:
e[::-1]

array([[1, 5, 3, 4],
       [1, 2, 2, 2]])

In [43]:
np.rot90(e)

array([[2, 4],
       [2, 3],
       [2, 5],
       [1, 1]])

In [44]:
ff = np.array([1,2,3,4,5,6,7,8,9,0])
gg = np.split(ff,2)
gg

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9, 0])]

In [45]:
hh = []
for i in gg:
    print(type(i))
    hh = hh + [i.tolist()]
hh

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

In [46]:
ii = np.array([[1,2],[1,2],[2,3],[2,3]])

In [47]:
jj = np.split(ii,2)

In [48]:
ll = []
for i in jj:
    ll = ll + [i]
ll

[array([[1, 2],
        [1, 2]]), array([[2, 3],
        [2, 3]])]

In [49]:
list(ll[0])+list(ll[1])

[array([1, 2]), array([1, 2]), array([2, 3]), array([2, 3])]

In [50]:
mm = []

In [51]:
mm + [1]

[1]

In [52]:
def eval_numerical_gradient(f, x):
  """ 
  a naive implementation of numerical gradient of f at x 
  - f should be a function that takes a single argument
  - x is the point (numpy array) to evaluate the gradient at
  """ 

  fx = f(x) # evaluate function value at original point
  grad = np.zeros(x.shape)
  h = 0.00001

  # iterate over all indexes in x
  it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
  while not it.finished:

    # evaluate function at x+h
    ix = it.multi_index
    old_value = x[ix]
    x[ix] = old_value + h # increment by h
    fxh = f(x) # evalute f(x + h)
    x[ix] = old_value # restore to previous value (very important!)

    # compute the partial derivative
    grad[ix] = (fxh - fx) / h # the slope
    it.iternext() # step to next dimension

  return grad

In [53]:
a = np.arange(6).reshape(2,3)
for x in np.nditer(a, order='F'):
    print (x)


for x in np.nditer(a.T, order='C'):
    print (x)

0
3
1
4
2
5
0
3
1
4
2
5


In [54]:
np.nditer(np.array([[1,2,3],[1,2,3],[1,2,3]]), flags=['multi_index'], op_flags=['readwrite']).finished

False

In [55]:
y = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])

In [56]:
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [58]:
np.array([[1],[2],[3]])

array([[1],
       [2],
       [3]])

In [59]:
z = np.array([[1],[2],[3]]) * np.ones((3,4))
z

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.]])

In [60]:
y[np.array([[0],[1],[2]]),np.array([[1],[2],[3]])]

array([[ 1],
       [ 7],
       [13]])

In [61]:
y[np.array([0,1,2]),np.array([1,2,3])]

array([ 1,  7, 13])

In [62]:
y[np.array([[0],[1],[2]]),np.array([[1],[2],[3]])]*np.ones((3,4))

array([[  1.,   1.,   1.,   1.],
       [  7.,   7.,   7.,   7.],
       [ 13.,  13.,  13.,  13.]])

In [63]:
np.arange(3)

array([0, 1, 2])

In [64]:
z = y
z [np.array([0,1,2]),np.array([1,2,3])] = 0
z

array([[ 0,  0,  2,  3,  4],
       [ 5,  6,  0,  8,  9],
       [10, 11, 12,  0, 14]])

In [65]:
z.reshape(3,5,1)

array([[[ 0],
        [ 0],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 0],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [ 0],
        [14]]])

In [66]:
z.reshape(3,5,1)

array([[[ 0],
        [ 0],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 0],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [ 0],
        [14]]])

In [67]:
sum(z)

array([15, 17, 14, 11, 27])

In [68]:
type(z > 0)

numpy.ndarray

In [69]:
z0 = (z>0)*1 #* np.array([[1,2,3],[4,5,6],[7,8,9]])
z0

array([[0, 0, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 1, 1, 0, 1]])

In [70]:
z0*np.array([2,2])

ValueError: operands could not be broadcast together with shapes (3,5) (2,) 

In [71]:
z1 = z0.reshape(3,5,1)
z1

array([[[0],
        [0],
        [1],
        [1],
        [1]],

       [[1],
        [1],
        [0],
        [1],
        [1]],

       [[1],
        [1],
        [1],
        [0],
        [1]]])

In [72]:
z1*np.array([1,2])

array([[[0, 0],
        [0, 0],
        [1, 2],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [0, 0],
        [1, 2],
        [1, 2]],

       [[1, 2],
        [1, 2],
        [1, 2],
        [0, 0],
        [1, 2]]])

In [73]:
z2 = np.dstack([np.array([[1,2],[3,4],[5,6]])]*2)
z2

array([[[1, 1],
        [2, 2]],

       [[3, 3],
        [4, 4]],

       [[5, 5],
        [6, 6]]])

In [74]:
z2[0]

array([[1, 1],
       [2, 2]])

In [75]:
z3 = np.array([[1, 2], [3, 4],[5,6],[7,8]])
print(z3.shape)
# (2,  2)

# indexing with np.newaxis inserts a new 3rd dimension, which we then repeat the
# array along, (you can achieve the same effect by indexing with None, see below)
z4 = np.repeat(z3[np.newaxis, :, :], 3, axis=2)
print(z4, '\n', z4.shape)

(4, 2)
[[[1 1 1 2 2 2]
  [3 3 3 4 4 4]
  [5 5 5 6 6 6]
  [7 7 7 8 8 8]]] 
 (1, 4, 6)


In [76]:
z4 = np.repeat(z3[ :, np.newaxis, :], 3, axis=2)
print(z4, '\n', z4.shape)

[[[1 1 1 2 2 2]]

 [[3 3 3 4 4 4]]

 [[5 5 5 6 6 6]]

 [[7 7 7 8 8 8]]] 
 (4, 1, 6)


In [77]:
z4 = np.repeat(z3[ :, :, np.newaxis], 3, axis=2)
print(z4, '\n', z4.shape)

[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]

 [[7 7 7]
  [8 8 8]]] 
 (4, 2, 3)


In [78]:
z4 = np.repeat(z3[np.newaxis, :, :], 3, axis=1)
print(z4, '\n', z4.shape)

[[[1 2]
  [1 2]
  [1 2]
  [3 4]
  [3 4]
  [3 4]
  [5 6]
  [5 6]
  [5 6]
  [7 8]
  [7 8]
  [7 8]]] 
 (1, 12, 2)


In [79]:
z4 = np.repeat(z3[ :, np.newaxis,:], 3, axis=1)
print(z4, '\n', z4.shape)

[[[1 2]
  [1 2]
  [1 2]]

 [[3 4]
  [3 4]
  [3 4]]

 [[5 6]
  [5 6]
  [5 6]]

 [[7 8]
  [7 8]
  [7 8]]] 
 (4, 3, 2)


In [80]:
z5 = (z4>5)*1
print(z5*z4)
print((z5*z4).shape)

[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 6]
  [0 6]
  [0 6]]

 [[7 8]
  [7 8]
  [7 8]]]
(4, 3, 2)


In [81]:
print(sum(z5*z4))
print(sum(z5*z4).shape)

[[ 7 14]
 [ 7 14]
 [ 7 14]]
(3, 2)


In [82]:
z7 = np.rot90(z5*z4)
z7

array([[[0, 0],
        [0, 0],
        [0, 6],
        [7, 8]],

       [[0, 0],
        [0, 0],
        [0, 6],
        [7, 8]],

       [[0, 0],
        [0, 0],
        [0, 6],
        [7, 8]]])

In [83]:
z7.shape

(3, 4, 2)

In [84]:
z4 = np.repeat(z3[ :,:, np.newaxis], 3, axis=1)
print(z4, '\n', z4.shape)

[[[1]
  [1]
  [1]
  [2]
  [2]
  [2]]

 [[3]
  [3]
  [3]
  [4]
  [4]
  [4]]

 [[5]
  [5]
  [5]
  [6]
  [6]
  [6]]

 [[7]
  [7]
  [7]
  [8]
  [8]
  [8]]] 
 (4, 6, 1)


In [85]:
z4 = np.repeat(z3[np.newaxis, :, :], 3, axis=0)
print(z4, '\n', z4.shape)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]

 [[1 2]
  [3 4]
  [5 6]
  [7 8]]

 [[1 2]
  [3 4]
  [5 6]
  [7 8]]] 
 (3, 4, 2)


In [86]:
z4 = np.repeat(z3[:, np.newaxis, :], 3, axis=0)
print(z4, '\n', z4.shape)

[[[1 2]]

 [[1 2]]

 [[1 2]]

 [[3 4]]

 [[3 4]]

 [[3 4]]

 [[5 6]]

 [[5 6]]

 [[5 6]]

 [[7 8]]

 [[7 8]]

 [[7 8]]] 
 (12, 1, 2)


In [87]:
z4 = np.repeat(z3[:, :, np.newaxis], 3, axis=0)
print(z4, '\n', z4.shape)

[[[1]
  [2]]

 [[1]
  [2]]

 [[1]
  [2]]

 [[3]
  [4]]

 [[3]
  [4]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[5]
  [6]]

 [[5]
  [6]]

 [[7]
  [8]]

 [[7]
  [8]]

 [[7]
  [8]]] 
 (12, 2, 1)


In [88]:
z7

array([[[0, 0],
        [0, 0],
        [0, 6],
        [7, 8]],

       [[0, 0],
        [0, 0],
        [0, 6],
        [7, 8]],

       [[0, 0],
        [0, 0],
        [0, 6],
        [7, 8]]])

In [89]:
np.column_stack([np.arange(10),np.arange(10)])

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [90]:
z10 = np.zeros((10,10))
z10[0,0]=1


In [91]:
z10

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [92]:
z11 = np.arange(10)
z11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.repeat(z11[np.newaxis, :], 2, axis=0)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [94]:
np.repeat(z11[np.newaxis, :], 2, axis=1)

array([[0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9]])

In [95]:
np.repeat(z11[ :, np.newaxis], 2, axis=1)

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [96]:
np.repeat(z11[ :, np.newaxis], 2, axis=0)

array([[0],
       [0],
       [1],
       [1],
       [2],
       [2],
       [3],
       [3],
       [4],
       [4],
       [5],
       [5],
       [6],
       [6],
       [7],
       [7],
       [8],
       [8],
       [9],
       [9]])

In [97]:
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]],[[19,20,21],[22,23,24]]])
a.shape

(4, 2, 3)

In [98]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [99]:
b = sum(a)
b

array([[40, 44, 48],
       [52, 56, 60]])

In [100]:
b.shape

(2, 3)

In [101]:
x = np.arange(10,1,-1)
print(x)

x[np.array([3, 3, 1, 8])]

[10  9  8  7  6  5  4  3  2]


array([7, 7, 9, 2])

In [102]:
len(x)

9

In [103]:
a[np.array([0,1,2])]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [104]:
ddd = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
ddd.shape

(3, 4)

In [105]:
ddd[np.array([1,2])].shape

(2, 4)

In [106]:
index_max = np.argmax(ddd, axis = 0)
index_max

array([2, 2, 2, 2])

In [107]:
import itertools

In [108]:
for i in itertools.product(ddd[0],ddd[0]):
    print(i)

(1, 1)
(1, 2)
(1, 3)
(1, 4)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(4, 1)
(4, 2)
(4, 3)
(4, 4)


In [109]:
for i, j in itertools.product(ddd[0],ddd[0]):
    print(i, j)


1 1
1 2
1 3
1 4
2 1
2 2
2 3
2 4
3 1
3 2
3 3
3 4
4 1
4 2
4 3
4 4


In [110]:
(index_max.T)

array([2, 2, 2, 2])

In [111]:
index_max

array([2, 2, 2, 2])

In [112]:
index_max.dot(np.rot90(np.array([[1,2,3,4],[5,6,7,8]])))

array([20, 52])

In [132]:
n=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
n

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [133]:
import time
t1 = time.time()
np.sum(n, axis =0 )
t2 = time.time()
t2-t1

0.00017142295837402344

In [134]:
import time
t1 = time.time()
sum(n)
t2 = time.time()
t2-t1

0.00020074844360351562

In [135]:
np.sum(n, axis =0 )

array([[ 6,  8],
       [10, 12]])

In [141]:
np.rot90(sum(n))

array([[ 8, 12],
       [ 6, 10]])

In [137]:
m = np.rot90(n)
sum(m)

array([[ 4,  6],
       [12, 14]])

In [140]:
np.sum(n, axis =1 )

array([[ 4,  6],
       [12, 14]])

In [149]:
import math
math.log(math.exp(1))

1.0

In [7]:
def softmax_loss_naive(W, X, y, reg):
  """
  Softmax loss function, naive implementation (with loops)

  Inputs have dimension D, there are C classes, and we operate on minibatches
  of N examples.

  Inputs:
  - W: A numpy array of shape (D, C) containing weights.
  - X: A numpy array of shape (N, D) containing a minibatch of data.
  - y: A numpy array of shape (N,) containing training labels; y[i] = c means
    that X[i] has label c, where 0 <= c < C.
  - reg: (float) regularization strength

  Returns a tuple of:
  - loss as single float
  - gradient with respect to weights W; an array of same shape as W
  """
  # Initialize the loss and gradient to zero.
  loss = 0.0
  dW = np.zeros_like(W)

  #############################################################################
  # TODO: Compute the softmax loss and its gradient using explicit loops.     #
  # Store the loss in loss and the gradient in dW. If you are not careful     #
  # here, it is easy to run into numeric instability. Don't forget the        #
  # regularization!                                                           #
  #############################################################################
  import math
  num_classes = W.shape[1]
  num_train = X.shape[0]
  # score = X.dot(W)
  for i in range(num_train):
    scores = X[i].dot(W)
    fyi = scores[y[i]]
    sum_efj = 0
    dW[i,:] = X[i]*np.exp(X[i].dot(W[:,:]))/np.sum(np.exp(X[i].dot(W[:,:])))
    for j in range(num_classes):
      sum_efj += math.exp(X[i].dot(W[:,j]))
    loss = loss - fyi + math.log(sum_efj)
    
                  
  loss = loss / num_train
  loss += reg * np.sum(W * W)
  dW = dW / num_train



  pass
  #############################################################################
  #                          END OF YOUR CODE                                 #
  #############################################################################

  return loss, dW



In [161]:
math.log(5)

1.6094379124341003

In [8]:
[(1+i*0.1)*1e4 for i in range(-3,3)] + [(2+0.1*i)*1e4 for i in range(-3,3)]

[7000.0,
 8000.0,
 9000.0,
 10000.0,
 11000.0,
 12000.0,
 17000.0,
 18000.0,
 19000.0,
 20000.0,
 21000.0,
 22000.0]

In [12]:
def softmax_loss_naive(W, X, y, reg):
  """
  Softmax loss function, naive implementation (with loops)

  Inputs have dimension D, there are C classes, and we operate on minibatches
  of N examples.

  Inputs:
  - W: A numpy array of shape (D, C) containing weights.
  - X: A numpy array of shape (N, D) containing a minibatch of data.
  - y: A numpy array of shape (N,) containing training labels; y[i] = c means
    that X[i] has label c, where 0 <= c < C.
  - reg: (float) regularization strength

  Returns a tuple of:
  - loss as single float
  - gradient with respect to weights W; an array of same shape as W
  """
  # Initialize the loss and gradient to zero.
  loss = 0.0
  dW = np.zeros_like(W)

  #############################################################################
  # TODO: Compute the softmax loss and its gradient using explicit loops.     #
  # Store the loss in loss and the gradient in dW. If you are not careful     #
  # here, it is easy to run into numeric instability. Don't forget the        #
  # regularization!                                                           #
  #############################################################################
  import math
  num_classes = W.shape[1]
  num_train = X.shape[0]
  # score = X.dot(W)
  for i in range(num_train):
      scores = X[i].dot(W)
      fyi = scores[y[i]]
      sum_efj = 0
      
      for j in range(num_classes):
            if j == y[i]:
                dW[:,j] -= X[:,j]
                
            sum_efj += math.exp(X[i].dot(W[:,j]))
            dW[:,j] += X[i,j]*np.exp(X[i].dot(W[:,j]))/np.sum(np.exp(X[i].dot(W)))
            # dW[:,j] += (X[i]*np.exp(X[i].dot(W[:,j]))/math.log(np.sum(np.exp(X[i].dot(W))))) / num_train 
            # dW[:, y[i]] -= X[i] / num_train 
      loss = loss - fyi + math.log(sum_efj)
    
                  
  loss = loss / num_train
  loss += reg * np.sum(W * W)
  dW /= num_train
  dW += reg* W   



  pass
  #############################################################################
  #                          END OF YOUR CODE                                 #
  #############################################################################

  return loss, dW



In [18]:
numpy.concatenate((numpy.array([0,1,2,3,4,5]),numpy.array([0,1,2,3,4,5])),axis=0)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5])

In [27]:
numpy.column_stack((numpy.array([0,1,2,3,4,5]),numpy.array([0,1,2,3,4,5])))

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [29]:
np.log(2)

0.69314718055994529

In [38]:
n=np.array([[1,2],[3,4],[5,6],[7,8]])
n

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
n[(0,1),(1,1)]

array([2, 4])

In [56]:
n[ np.array([0,0,1,1]), np.array([1,1,1,1] )]

array([2, 2, 4, 4])

In [63]:
n[:,np.array([0,1]) ]

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [65]:
n.T

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [67]:
n

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [71]:
np.sum(n,axis = 1)

array([ 3,  7, 11, 15])

In [73]:
n/np.array([[1],[2],[3],[4]])

array([[ 1.        ,  2.        ],
       [ 1.5       ,  2.        ],
       [ 1.66666667,  2.        ],
       [ 1.75      ,  2.        ]])

In [75]:
np.array([1,2,3,4]).reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [79]:
np.linalg.svd(np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]))

(array([[-0.20673589,  0.88915331,  0.40824829],
        [-0.51828874,  0.25438183, -0.81649658],
        [-0.82984158, -0.38038964,  0.40824829]]),
 array([  2.54368356e+01,   1.72261225e+00,   1.73014261e-15]),
 array([[-0.40361757, -0.46474413, -0.52587069, -0.58699725],
        [-0.73286619, -0.28984978,  0.15316664,  0.59618305],
        [ 0.5089281 , -0.82947951,  0.1321747 ,  0.1883767 ],
        [ 0.20246527,  0.10937892, -0.82615365,  0.51430946]]))

In [82]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [87]:
np.std(x, axis = 0)

array([ 3.26598632,  3.26598632,  3.26598632,  3.26598632])

In [95]:
x / np.std(x, axis = 0)

array([[ 0.30618622,  0.61237244,  0.91855865,  1.22474487],
       [ 1.53093109,  1.83711731,  2.14330352,  2.44948974],
       [ 2.75567596,  3.06186218,  3.3680484 ,  3.67423461]])

In [107]:
u,s,v = np.linalg.svd(x)

In [108]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
u,s,v

(array([[-0.20673589,  0.88915331,  0.40824829],
        [-0.51828874,  0.25438183, -0.81649658],
        [-0.82984158, -0.38038964,  0.40824829]]),
 array([  2.54368356e+01,   1.72261225e+00,   1.73014261e-15]),
 array([[-0.40361757, -0.46474413, -0.52587069, -0.58699725],
        [-0.73286619, -0.28984978,  0.15316664,  0.59618305],
        [ 0.5089281 , -0.82947951,  0.1321747 ,  0.1883767 ],
        [ 0.20246527,  0.10937892, -0.82615365,  0.51430946]]))

In [104]:
Xrot = np.dot(u,x)
Xrot

array([[  7.91326526,   9.00393097,  10.09459668,  11.18526238],
       [ -6.5948488 ,  -7.67525228,  -8.75565577,  -9.83605925],
       [  0.94244483,   0.1404619 ,  -0.66152104,  -1.46350397]])

In [112]:
np.dot(u,u)

array([[-0.75687983, -0.11292887, -0.64372354],
       [ 0.65286846, -0.08554119, -0.75262572],
       [ 0.0299283 , -0.98991402,  0.1384721 ]])